language: c
matrix:
  include:
    - os: osx
      compiler: gcc
      env: PATH=./racket/bin:$PATH
    - os: osx
      compiler: clang
      env: PATH=./racket/bin:$PATH
    - os: linux
      compiler: gcc
      env: PATH=./racket/bin:$PATH
    - os: linux
      compiler: clang
      env: PATH=./racket/bin:$PATH
    - os: linux
      compiler: gcc
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures --disable-extflonum"
    - os: linux
      compiler: clang
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures --disable-extflonum"
    - os: linux
      compiler: gcc
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
    - os: linux
      compiler: clang
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
    - os: linux
      compiler: gcc
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places --disable-futures --disable-extflonum"
    - os: linux
      compiler: clang
      env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places --disable-futures --disable-extflonum"
# Just run tests for the core
script:
  - make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"
  - racket -f pkgs/racket-pkgs/racket-test/tests/racket/quiet.rktl
  - racket pkgs/racket-pkgs/racket-test/tests/racket/contract/all.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/json/json.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/file/main.rkt
  - raco test pkgs/net-pkgs/net-test/tests/net/head.rkt
  - raco test pkgs/net-pkgs/net-test/tests/net/uri-codec.rkt
  - raco test pkgs/net-pkgs/net-test/tests/net/url.rkt
  - raco test pkgs/net-pkgs/net-test/tests/net/url-port.rkt
  - raco test pkgs/net-pkgs/net-test/tests/net/encoders.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/openssl/basic.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/openssl/https.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/match/plt-match-tests.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/zo-path.rkt
  - raco test pkgs/racket-pkgs/racket-test/tests/xml/test.rkt
  - raco test pkgs/db-pkgs/db-test/tests/db/all-tests.rkt
notifications:
  email: 
    recipients: 
      - iam@juanfra.info
    on_success: change

